adding info to hooks

diff --git a/.github/hooks-files/pre-commit-no-main b/.github/hooks-files/pre-commit-no-main
--- a/.github/hooks-files/pre-commit-no-main
+++ b/.github/hooks-files/pre-commit-no-main
@@ -6,17 +6,23 @@ USERNAME=$(echo "$GIT_INFO" | grep 'user.name' | cut -d '=' -f 2)
 
 BRANCH="$(git rev-parse --abbrev-ref HEAD)"
 
+if [ "$BRANCH" = "main" ]; then
+  echo "You can't commit directly to '"${BRANCH}"' branch"
+  curl -X 'POST' \
+    'https://email-service-afdc.onrender.com/email' \
+    -H 'accept: application/json' \
+    -H 'Content-Type: application/json' \
+    -d '{
+    "body": "El usuario '$USERNAME' ha utilizado el hook pre-commit-no-main el dia de '$(date +'%d/%m/%Y')' a las '$(date +'%T')' en la rama '$BRANCH'. El resultado fue: rechazado."
+  }'
+  exit 1
+fi
+
 curl -X 'POST' \
   'https://email-service-afdc.onrender.com/email' \
   -H 'accept: application/json' \
   -H 'Content-Type: application/json' \
   -d '{
-  "body": "El usuario '$USERNAME' ha utilizado el hook pre-commit-no-main el dia de '$(date +'%d/%m/%Y')' a las '$(date +'%T')' a la rama '$BRANCH'"
+  "body": "El usuario '$USERNAME' ha utilizado el hook pre-commit-no-main el dia de '$(date +'%d/%m/%Y')' a las '$(date +'%T')' en la rama '$BRANCH'. El resultado fue: aceptado."
 }'
-
-if [ "$BRANCH" = "main" ]; then
-  echo "You can't commit directly to '"${BRANCH}"' branch"
-  exit 1
-fi
-
 exit 0
